# Generated by Django 4.2.30 on 2026-07-13 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('model_used', models.CharField(default='mistral-large-latest', max_length=50)),
                ('executive_summary', models.TextField(blank=True, default='')),
                ('business_highlights', models.TextField(blank=True, default='')),
                ('risks', models.TextField(blank=True, default='')),
                ('opportunities', models.TextField(blank=True, default='')),
                ('recommendations', models.TextField(blank=True, default='')),
                ('conclusion', models.TextField(blank=True, default='')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='datasets.dataset')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
